In [ ]:
import pandas as pd 

In [ ]:
a = pd.read_csv("/home/vimarshc/Downloads/filenameX.csv", header=None).head(1000)
b = pd.read_csv('/home/vimarshc/Downloads/filenameY.csv', header=None).head(2000)

In [ ]:
def func(x):
    q = list(x)
    p = np.minimum(q, b)
    p = np.sum(p, axis=1)
    p = p/np.sum(q)
    
    return p.to_list()
    

In [ ]:
%%timeit
q = a.apply(func,axis=1)

11.6 s ± 409 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
from multiprocessing import  Pool
from functools import partial
import numpy as np

def parallelize(data, func, num_of_processes=8):
    data_split = np.array_split(data, num_of_processes)
    pool = Pool(num_of_processes)
    data = pd.concat(pool.map(func, data_split))
    pool.close()
    pool.join()
    return data

def run_on_subset(func, data_subset):
    return data_subset.apply(func, axis=1)

def parallelize_on_rows(data, func, num_of_processes=10):
    return parallelize(data, partial(run_on_subset, func), num_of_processes)


In [ ]:
%%timeit
q = parallelize_on_rows(a, func) 

8.1 s ± 106 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
ans = pd.DataFrame(a.list_some.to_list())

In [ ]:
ans

0       1     2       3      4     5    6       7       8       9    \
0   100.00    0.00  0.01    0.00   0.00  0.00  0.0    0.00    0.01    0.57   
1     0.00  100.00  0.00    0.00  11.54  0.00  0.0    7.69    0.00   84.62   
2   100.00    0.00  0.00  100.00   0.00  0.00  0.0    0.00    0.00  100.00   
3    31.58   21.05  0.00    0.00  21.05  5.26  0.0  100.00   36.84  100.00   
4    22.39    0.00  0.00    0.00   1.49  0.00  0.0   10.45  100.00   25.37   
..     ...     ...   ...     ...    ...   ...  ...     ...     ...     ...   
95   15.00    0.00  0.00    5.00   5.00  5.00  0.0   10.00    5.00   90.00   
96    4.12   37.11  0.00    1.03   7.22  0.00  0.0    7.22    3.09   98.97   
97    0.00   53.06  0.00    0.00  14.29  0.00  0.0   10.20    0.00  100.00   
98   10.00    0.00  0.00    0.00  10.00  0.00  0.0   20.00   10.00   90.00   
99   75.28    0.00  1.00    0.12   0.12  0.00  0.0    1.25    1.87   51.44   

    ...    190     191    192    193    194    195     196  197    198    199  
0   ...   0.00    0.00   0.01   0.01   0.03   0.00    0.00  0.0   0.18   0.00  
1   ...   9.62   23.08   0.00   0.00   0.00   0.00   78.85  0.0   0.00   0.00  
2   ...   0.00  100.00   0.00   0.00   0.00   0.00  100.00  0.0   0.00   0.00  
3   ...  15.79   21.05  42.11  36.84  15.79  15.79   31.58  0.0   0.00  15.79  
4   ...   0.00    0.00  13.43  11.94   7.46   7.46    2.99  0.0   4.48   2.99  
..  ...    ...     ...    ...    ...    ...    ...     ...  ...    ...    ...  
95  ...   0.00   25.00  20.00  15.00   5.00   5.00    5.00  0.0   0.00   5.00  
96  ...   5.15   16.49   3.09   3.09   0.00   1.03   55.67  0.0   0.00   3.09  
97  ...  12.24   24.49   0.00   0.00   0.00   0.00   77.55  0.0   0.00   0.00  
98  ...   0.00    0.00  20.00  20.00   0.00  10.00   10.00  0.0   0.00  10.00  
99  ...   0.00    0.37   1.37   1.00   4.24   0.62    0.37  0.0  27.59   0.50  

[100 rows x 200 columns]

In [ ]:
# -*- coding: utf-8 -*-
"""

Created on Sun Sep 13 22:55:17 2020
#copy of original

@author: rccheruk
"""
# import odin





"""
Executing the code
"""
######################
# Manager Lookup
######################
#
# print("Nope Execution started at: ", now1)
# # send_chime(" Execution started on TPTSkunkworks EC2")
# lookup = generateManagerLookup(minJobLevel=7, filterPMT7=0)
# jobTitleDistribution = prepInput()
######################
# Distance Metrics
######################


now1 = datetime.now()

X1=X.to_numpy()
Y1=Y.to_numpy()
Xs = np.sum(X1, axis=1)
Xd = np.zeros((X1.shape[0], Y1.shape[0]))

i = 0
while (i < X1.shape[0]):
    overlap_matrix_transformation(i)
    i=i+1

ModuleNotFoundError: No module named 'boto3'

In [ ]:
X.shape

(3273, 1896)

In [ ]:
Y.shape

(14745, 1896)

In [ ]:
X.head()

0     1     2     3     4     5     6     7     8     9     ...  1886  \
0     0     0     0     0     0     0     5     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   1887  1888  1889  1890  1891  1892  1893  1894  1895  
0     0     0     0     0     0     0     0     0    13  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     1     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  

[5 rows x 1896 columns]

In [ ]:
Y.head()

0     1     2     3     4     5     6     7     8     9     ...  1886  \
0     0     0     0     0     0     0     5     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   1887  1888  1889  1890  1891  1892  1893  1894  1895  
0     0     0     0     0     0     0     0     0    13  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  

[5 rows x 1896 columns]

In [ ]:
def overlap_matrix_transformation(i):
    global X1
    global Y1
    global Xs
    global Xd
    Xd[i][:] = (np.sum(np.minimum(X1[i], Y1), axis=1)) / Xs[i]
    Xd[i][:]=np.round(Xd[i][:]*100,2)

    # return Xd

In [ ]:
import boto3
import platform
from datetime import datetime
import pandas as pd
import numpy as np
import requests
import io
from joblib import Parallel,delayed
import multiprocessing
import concurrent.futures

from sklearn.metrics.pairwise import pairwise_distances

In [ ]:
now1 = datetime.now()
X = pd.read_csv("/home/vimarshc/Downloads/filenameX.csv", header=None)
Y = pd.read_csv('/home/vimarshc/Downloads/filenameY.csv', header=None)

# X = filterData(7, 1)
# Y = filterData(7, 0)
# # X.to_csv('filenameX.csv', header=False, index=False)
# # Y.to_csv('filenameY.csv', header=False, index=False)


# now2 = datetime.now()
# print("X size is", X.shape, Y.shape)
# print("Data prep done: ", now2 - now1)
# send_chime(" Data prep done")


Data prep done:  0:00:01.967493


In [ ]:
a = X.head(100)

In [ ]:
b = Y.head(200)

In [ ]:
a.head()

0     1     2     3     4     5     6     7     8     9     ...  1886  \
0     0     0     0     0     0     0     5     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   1887  1888  1889  1890  1891  1892  1893  1894  1895  
0     0     0     0     0     0     0     0     0    13  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     1     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  

[5 rows x 1896 columns]

In [ ]:
b.head()

0     1     2     3     4     5     6     7     8     9     ...  1886  \
0     0     0     0     0     0     0     5     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   1887  1888  1889  1890  1891  1892  1893  1894  1895  
0     0     0     0     0     0     0     0     0    13  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  

[5 rows x 1896 columns]

In [ ]:
a['list_x'] = a.apply(lambda x: (np.sum(np.minimum(list(x), b), axis=1)) / np.sum(list(x)),axis=1)

ValueError: Wrong number of items passed 20, placement implies 1

In [ ]:
X['sum'] = X.apply(lambda x: (np.sum(np.minimum(list(x), Y), axis=1)) / np.sum(list(x)),axis=1)

KeyboardInterrupt: 

In [ ]:
a = pd.DataFrame({'1':[1,1],'2':[2,3]})
b = pd.DataFrame({'1':[5,4],'2':[1,3]})

In [ ]:
a = pd.read_csv("/home/vimarshc/Downloads/filenameX.csv", header=None)
b = pd.read_csv('/home/vimarshc/Downloads/filenameY.csv', header=None)

In [ ]:
def func(x):
    p = np.minimum(list(x), b)
    p = np.sum(p, axis=1)
    p = p/np.sum(list(x))
    
    return p.to_list()
    

In [ ]:
# a['list_x'] = a.apply(func,axis=1)

In [ ]:
from multiprocessing import  Pool
from functools import partial
import numpy as np

def parallelize(data, func, num_of_processes=8):
    data_split = np.array_split(data, num_of_processes)
    pool = Pool(num_of_processes)
    data = pd.concat(pool.map(func, data_split))
    pool.close()
    pool.join()
    return data

def run_on_subset(func, data_subset):
    return data_subset.apply(func, axis=1)

def parallelize_on_rows(data, func, num_of_processes=8):
    return parallelize(data, partial(run_on_subset, func), num_of_processes)


In [ ]:
a['list_some'] = parallelize_on_rows(a, func) 

Process ForkPoolWorker-24:


KeyboardInterrupt: 

Process ForkPoolWorker-25:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/vimarshc/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/vimarshc/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/vimarshc/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vimarshc/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vimarshc/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/vimarshc/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/vimarshc/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File

  File "<ipython-input-168-e5a0b35e3a9e>", line 14, in run_on_subset
    return data_subset.apply(func, axis=1)
  File "/home/vimarshc/anaconda3/lib/python3.8/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/home/vimarshc/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/vimarshc/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 6878, in apply
    return op.get_result()
  File "/home/vimarshc/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 6878, in apply
    return op.get_result()
Traceback (most recent call last):
  File "/home/vimarshc/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/vimarshc/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/vimarshc/anaconda3/lib/python3.8/site-packages/pandas/core/apply.p

In [ ]:
a

0  1  2  3  4  5  6  7  8  9  ...  1887  1888  1889  1890  1891  1892  \
0   0  0  0  0  0  0  5  0  0  0  ...     0     0     0     0     0     0   
1   0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
2   0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
3   0  0  0  0  0  0  0  0  0  0  ...     0     0     0     1     0     0   
4   0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
.. .. .. .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   ...   ...   
95  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
96  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
97  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
98  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   
99  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0     0   

    1893  1894  1895                                          list_some  
0      0     0    13  [1.0, 0.0, 6.645843025187745e-05, 7.3842700279...  
1      0     0     0  [0.0, 1.0, 0.0, 0.0, 0.11538461538461539, 0.0,...  
2      0     0     0  [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3      0     0     0  [0.3157894736842105, 0.21052631578947367, 0.0,...  
4      0     0     0  [0.22388059701492538, 0.0, 0.0, 0.0, 0.0149253...  
..   ...   ...   ...                                                ...  
95     0     0     0  [0.15, 0.0, 0.0, 0.05, 0.05, 0.05, 0.0, 0.1, 0...  
96     0     0     0  [0.041237113402061855, 0.3711340206185567, 0.0...  
97     0     0     0  [0.0, 0.5306122448979592, 0.0, 0.0, 0.14285714...  
98     0     0     0  [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.2, 0.1, ...  
99     0     0     0  [0.7528089887640449, 0.0, 0.009987515605493134...  

[100 rows x 1897 columns]

In [ ]:
a

1  2                     list_x
0  1  2  [0.6666666666666666, 1.0]
1  1  3                 [0.5, 1.0]

In [ ]:

X1=a.to_numpy()
Y1=b.to_numpy()
Xs = np.sum(X1, axis=1)
Xd = np.zeros((X1.shape[0], Y1.shape[0]))

i = 0
while (i < X1.shape[0]):
    overlap_matrix_transformation(i)
    i=i+1

In [ ]:
Xd

array([[0.66666667, 1.        ],
       [0.5       , 1.        ]])

In [ ]:
X1=X.to_numpy()
Y1=Y.to_numpy()

In [ ]:
X1

array([[ 0,  0,  0, ...,  0,  0, 13],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [ ]:
Xs = np.sum(X1, axis=1)

In [ ]:
Xs

array([135423,     52,      1, ...,      8,      9,    135])

In [ ]:
X1.head(1).sum(axis=1)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [ ]:
X.sum(axis=1).reset_index()

index       0
0         0  135423
1         1      52
2         2       1
3         3      19
4         4      67
...     ...     ...
3268   3268      16
3269   3269    5340
3270   3270       8
3271   3271       9
3272   3272     135

[3273 rows x 2 columns]

In [ ]:

X1=X.to_numpy()
Y1=Y.to_numpy()
Xs = np.sum(X1, axis=1)
Xd = np.zeros((X1.shape[0], Y1.shape[0]))

i = 0
while (i < X1.shape[0]):
    overlap_matrix_transformation(i)
    i=i+1

NameError: name 'time2' is not defined

In [ ]:
a = pd.DataFrame({'1':[1,1],'2':[2,3]})
b = pd.DataFrame({'1':[5],'2':[1]})

In [ ]:
a.head()

1  2                   sum
0  1  2  [0.6666666666666666]
1  1  3                 [0.5]

In [ ]:
Xd

array([[0.66666667],
       [0.5       ]])

10

In [ ]:
global X1
global Y1
global Xs
global Xd

In [ ]:
def overlap_matrix_transformation(i):
    Xd[i][:] = (np.sum(np.minimum(X1[i], Y1), axis=1)) / Xs[i]
#     Xd[i][:]=np.round(Xd[i][:]*100,2)

    # return Xd

In [ ]:
def func(x):
    np.sum(np.minimum(X1[i], Y1), axis=1)) / Xs[i]

In [ ]:
X['y_list'] = X.apply(func)

0     1     2     3     4     5     6     7     8     9     ...  1886  \
0     0     0     0     0     0     0     5     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   1887  1888  1889  1890  1891  1892  1893  1894  1895  
0     0     0     0     0     0     0     0     0    13  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     1     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  

[5 rows x 1896 columns]

In [ ]:
Y.head()

0     1     2     3     4     5     6     7     8     9     ...  1886  \
0     0     0     0     0     0     0     5     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   1887  1888  1889  1890  1891  1892  1893  1894  1895  
0     0     0     0     0     0     0     0     0    13  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  

[5 rows x 1896 columns]

In [ ]:
np.minimum(X1[0], Y1)

array([[1, 1]])

In [ ]:
np.minimum([6,2], [[5,1],[7,3]])

array([[5, 1],
       [6, 2]])

In [ ]:
np.sum(np.minimum([6,2], [[5,1],[7,3]]),axis=1)

array([6, 8])

In [ ]:
X1[0]

array([1, 2])

In [ ]:
Y1

array([[5, 1]])

In [ ]:

X1=a.to_numpy()
Y1=b.to_numpy()
Xs = np.sum(X1, axis=1)
Xd = np.zeros((X1.shape[0], Y1.shape[0]))



In [ ]:
i = 0
while (i < X1.shape[0]):
    overlap_matrix_transformation(i)
    i=i+1

In [ ]:
Xd

array([[0.66666667],
       [0.5       ]])

In [ ]:
Xs

array([1, 1, 2, 2])

In [ ]:
a

1
0  1
1  1
2  2
3  2

In [ ]:
b

1
0  5
1  4